version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    links:
      - backend
  backend:
    build: ./backend
    env_file:
      - backend.env
    links:
      - mssql
  mssql:
    build: ./mssql
    env_file:
      - mssql.env
    ports:
      - "1433:1433"